language: php
php:
  - 5.6
  - 7.2

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
  - composer self-update -q
  - travis_retry composer install

jobs:
  include:
    - stage: PHP Lint
      php: 7.2
      install:
        - phpenv config-rm xdebug.ini
      script:
        - if find . -type f -name "*.php" ! -path "./vendor/*" | xargs -n 1 -P 8 -I % php -d error_reporting=32767 -l % \; 2>&1 >&- | grep "^" ; then exit 1; fi
    - stage: PHP CS Fixer
      php: 7.2
      install:
        - phpenv config-rm xdebug.ini
      script:
        - vendor/bin/php-cs-fixer fix --dry-run -v --show-progress=dots --diff-format=udiff